# Generated by Django 4.2.3 on 2023-07-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_created_at_topic_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='body',
        ),
    ]
